### ISSUE TITLE
Dependency on Adobe servers on first load

### ISSUE THREAD

**Issue by KrisAnimate** [Wrapper-Offline/wrapper-offline#121]
The main SWFs for Wrapper (in `server\animation`) are built on Apache Flex and require 6 SWZ files. If these SWZs have not been previously cached, or such cache has been cleared, these SWZs need to be loaded from either Adobe servers or the same folder as the SWFs. We do not know for certain until when will Adobe keep those SWZ files on their servers. If these SWZ files could not be loaded, the LVM will refuse to work at all.

These SWZs are:
``framework_4.6.0.23201.swz``
``mx_4.6.0.23201.swz``
``rpc_4.6.0.23201.swz``
``spark_4.6.0.23201.swz``
``sparkskins_4.6.0.23201.swz``
``textLayout_2.0.0.232.swz``

The beta build of Wrapper: Offline has, at the time of writing, 5 of those SWZ files in ``server\animation``. For some reason, ``rpc_4.6.0.23201.swz`` is missing from there. I suspect it was mistaken for something related to Discord RPC.

**Comment by RegularSpark** [comment]
I'm not sure why these aren't here, I'll add them when I get on my laptop.
