### ISSUE TITLE
"VoiceForge voices still don't work, they'll be removed in the next update." lol it's a cap lol

### ISSUE THREAD

**Issue by ffa220** [wrapper-offline/wrapper-offline#123]
when i'm opening wrapper offline make a video i select comedy world and i click background i click text-to-speech voices i click shouty
(Shouty is a VoiceForge tts) and i type "test" and generate, and...
### OMG! VOICEFORE LOL SHOUTY'S TTS, IT FINALLY LISTENED! NO MORE UPDATES ON VOICEFORGE!!!

and... that's it!

**Comment by AQ206** [comment]
actually the voice in question came from cepstral, as you can see in the voices.json
![image](https://user-images.githubusercontent.com/73343488/216266104-7ba62033-89bc-431b-ac44-8f21c9cebd02.png)

the site only has a portion of the voices from voiceforge, so the other voiceforge voices still don't work
