### ISSUE TITLE
can you add voiceforge voices back

### ISSUE THREAD

**Issue by barnicaleboy09** [wrapper-offline/wrapper-offline#129]
can you please add them back i really need to use diesel kidaroo princess and kayla for my videos
only if you can though because i know servers went down but flash themes has them so im sure you can find a way to get them back so please add them back in the next update thank you

btw i also need toilet paper my mom spanked me too hard and i had an accident all over the walls

**Comment by octanuary** [comment]
no we can't

**Comment by barnicaleboy09** [comment]
doesn't flash themes have designer dave and diesel voices? those are only voiceforge voices how is that possible for them to have it?
