### ISSUE TITLE
Too many Actions clogged or failed to load in Comedy world and Lil Peepz; Need to put the Action list

### ISSUE THREAD

**Issue by MomfroxUB4hnZ** [wrapper-offline/wrapper-offline#134]
I have a feeling when the Actions tab Failed or too cloggy to load while loading too many of actions and expressions in Comedy world and lil peepz. To do this to solve the problem, I proposed an idea to put this on the tab:

![2023-02-11_005048_Make a list](https://user-images.githubusercontent.com/114128345/218151702-15ac9b3e-9772-400d-8460-9694b9f4f9cb.png)

**Comment by octanuary** [comment]
that's impossible to add
