### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JBanimater700** [wrapper-offline/wrapper-offline#156]
I wanted to download WrapperOffline for my MacBook, but I couldn’t find the download. It was showing Windows and Linux downloads, but not MacOS. I was really looking forward to using Comedy World for the first time since Vyond doesn’t have it anymore. Can you tell me what's going on? I hope it becomes available again.

**Comment by SimplyA-Coder** [comment]
Questions aren't an issue, but I do know a YouTube video on it: https://youtu.be/FcG4wY57JdA

**Comment by 2Epik4u** [comment]
there's a mac build now
