### ISSUE TITLE
Export Video

### ISSUE THREAD

**Issue by LanzPalermo** [wrapper-offline/wrapper-offline#161]
So I'm trying to export a video to an mp4 file, and there is no feature on that. Can you add this feature in a future update so I can make videos like this and upload them to my youtube channel, I used to make videos like this when I was a kid.

**Comment by SimplyA-Coder** [comment]
If you have never heard before, Wrapper: Offline is a revival of GoAnimate.com, as it is no longer supported.
They used files that we can't use or couldn't find for video exporting, so we can't add that feature at the moment.

**Comment by octanuary** [comment]
no

**Comment by SimplyA-Coder** [comment]
Never mind, Wrapper: Offline just added Video exporting in its latest v2.1.0 release! You can download it from https://github.com/Wrapper-Offline/Wrapper-Offline/archive/refs/heads/main.zip
