### ISSUE TITLE
Add more poses to the Business Friendly section of Wrapper Offline

### ISSUE THREAD

**Issue by abhiramakella** [wrapper-offline/wrapper-offline#181]

**Comment by SimplyA-Coder** [comment]
That's not much of an issue, they would have to do Shockwave Flash file decoding or something similar. You could try to do it by going to server/store/3a981f5cb2739137/cc_store/business, then download Adobe Animate or JPEXS Free Flash Decompiler. Add some movement sprites, then to make it move, navigate to the scripts category and start scripting. (It should be for every body part when used for the action).
