### ISSUE TITLE
(linux) Can't find electron 

### ISSUE THREAD

**Issue by NXX99** [wrapper-offline/wrapper-offline#189]
Every time I run NPM Start or NPM Build, shows this:
![image](https://github.com/Wrapper-Offline/Wrapper-Offline/assets/91738741/877aa3d8-3062-44bf-bb9d-da4150a79dbf)
What do I do?

**Comment by octanuary** [comment]
`npm install`

**Comment by NXX99** [comment]
> `npm install`

Thank you very much!
