### ISSUE TITLE
TTS voices only say a single "wah" when crying

### ISSUE THREAD

**Issue by OperationVatterott** [wrapper-offline/wrapper-offline#217]
I can type "waaaaaaaaaaaaaaaa" into the input box for any TTS voice, and all it does is a single "wah". How can this be fixed?

(This is my first issue, so I'm not used to the GitHub issue system.)

**Comment by SimplyA-Coder** [comment]
Okay, first off, this is DEFINITELY NOT a Wrapper: Offline issue, this is the text-to-speech issue. It seems you are using a Polly voice, as the API associated with the voices only convert a spammed crying quote into a "wah". ReadLoud voices have the old 2015 Polly API so you can use that website for the old voices (they have waaaaaaaaaaaaaaas converted into waaaaaaaaaaaaaaas).

**Comment by OperationVatterott** [comment]
I tried readloud.net, and it worked. This issue also happens with the VoiceForge voices.

**Comment by SimplyA-Coder** [comment]
The new VoiceForge API has also been updated from it's old API from the early 2010s where typing "waaaaaaaaaaaaaaaaaaa" would end up as how you wanted but now it says a single wa. To do this, just type wa a a a a a a a a a a a a a a a a a a a a a a a a or something.

**Comment by octanuary** [comment]
wrapper offline can only forward tts requests to the actual software. how the tts synthesizes speech is out of our control.
