### ISSUE TITLE
Ungoogled Chromium says Flash isn't supported

### ISSUE THREAD

**Issue by KiaWeb** [wrapper-offline/wrapper-offline#23]
Wrapper Offline has started Ungoogled Chromium (chrome.exe) however when I try to make a video, it says not supported. Can anybody help me?

**Comment by michelle1574** [comment]
You give bugs on Discord, the server invite: https://discord.gg/Kf7BzSw

**Comment by KiaWeb** [comment]
Fix is install flash 18.0.0.194, and I did some stuff and it worked.
