### ISSUE TITLE
Cant load character creator

### ISSUE THREAD

**Issue by ghost** [wrapper-offline/wrapper-offline#24]
I cant launch character creator. it says
Unable to access the site
The localhost site does not allow you to establish a connection.
Try to do the following:

Check your internet connection.
Check the proxy server and firewall settings.
ERR_CONNECTION_REFUSED

Windows 11
Ungoogled Chrome
Version: Beta 1.3.0

**Comment by NanaMizukiAnother7** [comment]
I think that the npm program has been crashed.

**Comment by NolanJTheSuperGoAnimator** [comment]
Well then I think you might as well download Node.js version 14.17.0. Then see if it works or not.
