### ISSUE TITLE
Wrapper Offline Exporter Video doesn't work.  Wish you could download the video into any of these files:

### ISSUE THREAD

**Issue by goanimator722** [wrapper-offline/wrapper-offline#262]

**Comment by goanimator722** [comment]
Wrapper Offline Exporter Video doesn't work. Wish you could download the video into any of these files: 

.MOV
.MPEG-1
.MPEG-2
.MPEG4
.MP4
.MPG
.AVI
.WMV
.MPEGPS
.FLV
3GPP
WebM
DNxHR
ProRes
CineForm
HEVC (h265)

Maybe while you preview the video,

you could right click the video,

it says download,

it chooses which file to download or as a gif, just like in vyond.

you choose the file you want,

and boom!  you can upload it to youtube.

could someone please do this on the wrapper offline team?

**Comment by goanimator722** [comment]
What I mean is that for any version of wrapper,

the download could be easier.

**Comment by goanimator722** [comment]
2.1.0 wrapper exporter never works.

**Comment by goanimator722** [comment]
like it would be even easier than the exporter

**Comment by goanimator722** [comment]
if anyone sees this, will they please share this to the wrapper offline team?  i really want this so badly!  please?

**Comment by octanuary** [comment]
the exporter is unfinished, please don't make issues on it yet
