### ISSUE TITLE
Wrapper Offline does not work

### ISSUE THREAD

**Issue by goanimator722** [wrapper-offline/wrapper-offline#267]
Wrapper Offline 2.1.0 does not work

The video maker, the character creator, and the video previewing has just stopped working!

Please help.  I really want to make videos badly!

**Comment by goanimator722** [comment]
and also, how do you use the exporter.  could someone make a step by step video on how to?

**Comment by EthanAnimate** [comment]
same happening with me too

**Comment by goanimator722** [comment]
> [EthanAnimate](/EthanAnimate)

Can you make a video on how to export a wrapper offline video?
