### ISSUE TITLE
formidable 1.2.2 is deprecated

### ISSUE THREAD

**Issue by octanuary** [wrapper-offline/wrapper-offline#29]
**Describe the bug**
Wrapper: Offline v1.3.0 uses an old version of Formidable, which has been deprecated.

**Comment by GoTest334** [comment]
Not a high-priority issue from what I see. But can be updated when we get around to it

**Comment by octanuary** [comment]
https://github.com/Wrapper-Offline/Wrapper-Offline/commit/66f41178a34cb979fab9b8dde809a7345eb8544a

**Comment by GoTest334** [comment]
Alright good
