### ISSUE TITLE
To bring to Mac OS

### ISSUE THREAD

**Issue by HatcheryRoosters** [wrapper-offline/wrapper-offline#3]
Mac OS users like me should be able to use this as well, someone should make a DMG file, which lets us open the app

**Comment by michelle1574** [comment]
This is not app like exe file. It's based from bat files and can't be converted to dmg

**Comment by ghost** [comment]
we'll do it soon enough

**Comment by KiaWeb** [comment]
Use CodeWeavers' Crossover here: https://www.codeweavers.com/
It lets you run Windows stuff on Chrome, MacOS and linux.
