### ISSUE TITLE
Issue with pre-made Comedy World Characters not showing up when viewing the video

### ISSUE THREAD

**Issue by dotthefox** [wrapper-offline/wrapper-offline#30]
**Describe the bug**
The pre-made characters in Comedy World (mainly known as the Stock Characters) do not seem to load when viewing a video from the video list, loading a starter that contains a stock character, and editing a video that contained a stock character.

**To Reproduce**
1. Add any stock character from either the Ga4s stock characters tab, the Goanimators tab, the Stock characters tab, the Submissions tab, or the Credits tab into your video.
2. Save the video.
3. Go to the video list and watch the video

**Expected behavior**
The stock character will not show

**Screenshots**
![image](https://user-images.githubusercontent.com/32345566/165666094-0b187c07-7ec1-44b8-ba35-0d78b6bb9e30.png)
![image](https://user-images.githubusercontent.com/32345566/165666133-34a715f9-bef9-4d0c-a85e-b3a746bcfe1d.png)
![image](https://user-images.githubusercontent.com/32345566/165666219-eb6baf94-28e4-4e3a-81a2-536836eb0c27.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Ungoogled Chromium
 - Version Beta 1.3.0
 - NPM Crash Log [Turn on Verbose Mode to see NPM]

**Additional context**

The NPM doesn't crash, however, it does mention how it fails to load the character, shown here.
![image](https://user-images.githubusercontent.com/32345566/165665642-8b319e73-d83b-4944-88ea-caedcb31479d.png)

Text version: 

POST /goapi/getCcCharCompositionXml/
Loading character: 325084254
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084241
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084260
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084270
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084290
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084283
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084277
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084296
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084304
Character doesn't exist. Loading as stock char...
POST /goapi/getCcCharCompositionXml/
Loading character: 325084300
Character doesn't exist. Loading as stock char...

When you view a video, it states that the character is from an asset metadata that appears to be missing, shown here. 
![image](https://user-images.githubusercontent.com/32345566/165665795-0a4fa5b8-978c-41cd-a01b-aa1cfa6103f1.png)

Text version: 
GET /player?movieId=bb9236d
GET /pages/css/modern-normalize.css
GET /pages/css/global.css
GET /pages/css/flash.css
POST /goapi/getMovieInfo/
POST /goapi/getMovieInfo/
[ 'custom', 'bg', 'bedroom_bg.swf' ]
custom.bg.bedroom_bg.swf
POST /goapi/getMovie/?movieId=bb9236d&ut=60&userId=null
Character doesn't exist. Loading as stock char...
Asset metadata doesn't exist! Asset id: 874645
Asset metadata doesn't exist!
[ 'custom', 'prop', 'bedroom_blanket_bed.swf' ]
custom.prop.bedroom_blanket_bed.swf
[ 'custom', 'prop', 'bedroom_lamp.swf' ]
custom.prop.bedroom_lamp.swf
[ 'custom', 'prop', 'bedroom_drawer02.swf' ]
custom.prop.bedroom_drawer02.swf

By the way, the same "Asset metadata doesn't exist!" error will show if you were to save a stock character from CW into a starter and load it.

**Comment by octanuary** [comment]
This has been fixed in a recent commit.
