### ISSUE TITLE
Imported Assets tab does not load

### ISSUE THREAD

**Issue by andyw1589** [wrapper-offline/wrapper-offline#31]
When you try to open Imported Assets, it seems to freeze and never loads.

I managed to fix this myself by giving it a cc_theme_id of "import" in Wrapper-Offline\wrapper\\_THEMES\themelist.xml

Might have to do the same thing in themelist-allthemes.xml

Here's what I changed the imported asset's xml entry to:
![image](https://user-images.githubusercontent.com/46545759/168405538-13ed5a73-e9d0-4124-a5e7-098b6f3517b7.png)

**Comment by andyw1589** [comment]
apologies if this should be a pull request or something, i'm not that versed in using github :P

**Comment by GoTest334** [comment]
Question. Did this relate to importing custom audio or importing images?

**Comment by andyw1589** [comment]
I only tried it with audio.

**Comment by andyw1589** [comment]
I used the start_wrapper batch file to import it.

I also noticed that the import script edits Wrapper-Offline\server\store\3a981f5cb2739137\import\theme.xml, but it doesn't edit Wrapper-Offline\wrapper\\_THEMES\import.xml

After importing the audio, I had to manually copy the xml text into _THEMES\import.xml for it to actually show up.

**Comment by GoTest334** [comment]
does it fix this problem with importing audio?

https://cdn.discordapp.com/attachments/952043617143377981/974820421620891668/2022-05-13_19-44-51.mp4

**Comment by andyw1589** [comment]
Hmm, I should mention that this is for v1.2.3

**Comment by GoTest334** [comment]
Yes, and that is what i am using to trouble shoot this problem

**Comment by andyw1589** [comment]
The Imported Assets tab appears in a different location for me

**Comment by GoTest334** [comment]
Thats because i installed a business-friendly mod to it. Just ignore that, its the normal 1.2.3 lol

**Comment by GoTest334** [comment]
Also after testing. Your fix did not work. the video maker still soft locks after importing audio. Could you possibly send me a screen recording of you showing off your fix? so i can verify something

**Comment by andyw1589** [comment]
To be honest, I wasn't even aware that that was a bug. The original bug I was targeting was that this tab wouldn't even load at all:
![image](https://user-images.githubusercontent.com/46545759/168406338-66be878b-0023-4f96-bb29-635fea776616.png)

**Comment by GoTest334** [comment]
oh. I'm unsure why that happened to you. The imported assets tab always loaded for me and everyone else, sounds like a you problem.

**Comment by andyw1589** [comment]
that sure is strange
