### ISSUE TITLE
Voiceforge error

### ISSUE THREAD

**Issue by rryan22** [wrapper-offline/wrapper-offline#33]
When I click the "Generate Voice" button and it says something went wrong! Can you fix it?

**Comment by octanuary** [comment]
Do you have LAME installed and in the `PATH` environment variable?

**Comment by rryan22** [comment]
Yes, but it's not working on 1.3.0. Can you please fix it now?

**Comment by GoTest334** [comment]
Wrapper offline 1.3.0 beta functionality and stability are not approved and are not recommended for making videos at the moment. If you plan to be making videos, it's strongly recommended & advised you use Wrapper Offline 1.2.3 until 1.3.0 is out of its beta phase.

**Comment by rryan22** [comment]
I have Wrapper Offline 1.3.0 installed because it's still beta phase! Can you add Acapela Salma and Youssef Arabic voices to Wrapper Offline 1.3.0?
