### ISSUE TITLE
Cannot load the page

### ISSUE THREAD

**Issue by WindowsFan2006** [wrapper-offline/wrapper-offline#35]
It just displays the error ERR_CONNECTION_REFUSED.

**Comment by GoTest334** [comment]
Make sure you are using 1.2.3 and that you uninstall any versions of node, git, and flash, and then let the installer install the dedicated versions for you

**Comment by LillianaxAnderson** [comment]
I have a similar problem but everything works on it except the character creator, video maker and video player
