### ISSUE TITLE
Copy character bug

### ISSUE THREAD

**Issue by rryan22** [wrapper-offline/wrapper-offline#36]
Look! When I copy the character, it shows getCcCharCompositionXml not found! Can you please fix it now?

**Comment by rryan22** [comment]
I also have a screenshot! See this! 
![image](https://user-images.githubusercontent.com/60328548/172118805-89a85822-80a0-481e-9cdf-4141b22406a8.png)

**Comment by octanuary** [comment]
fixed
https://github.com/Wrapper-Offline/Wrapper-Offline/commit/b83c21999e0aa676c3815e4780235cae23818dc3
