### ISSUE TITLE
Editing character bug

### ISSUE THREAD

**Issue by rryan22** [wrapper-offline/wrapper-offline#37]
Look! When I click on Edit Info icon, and the Edit Info will freeze the legacy video maker! Can you please fix it now! Here! 
![image](https://user-images.githubusercontent.com/60328548/172794649-376dd2af-0b79-4c34-a74a-bb4d1bf8671e.png)

**Comment by rryan22** [comment]
It is fixed anyway!

**Comment by Jgamesandstuff** [comment]
no it ain't
it is broke for me
and i didn't save lol
