### ISSUE TITLE
After I made this video without reload page, and the characters won't load.

### ISSUE THREAD

**Issue by ChineseScoutGoAnimateYT** [Wrapper-Offline/wrapper-offline#42]
Can everyone help me?!

**Comment by CrystalVulpine** [comment]
This seems to be an issue when first loading new characters. Try restarting the program. There will be times when the sound is disabled too.

**Comment by zoccorus** [comment]
nvm it load!

**Comment by zoccorus** [comment]
@RegularSpark close this

**Comment by RegularSpark** [comment]
SHUT THE FUCK UP WHY DID YOU SPAM PING ME
