### ISSUE TITLE
Character creator, video maker and video player not loading

### ISSUE THREAD

**Issue by LillianaxAnderson** [wrapper-offline/wrapper-offline#43]
**Describe the bug**
When I go to make a video or a character or watch any of my videos it just shows a blank page, I have even tried different versions of flash player and node.js but it always ends up doing the same thing (I even reloaded the page and restarted the browser and my computer but it still shows the same thing)

**To Reproduce**
1. Go to 'Make a Character or Make a Video'
2. Click on 'Allow Flash Player'

**Expected behavior**
It's supposed to show the video maker when making/editing a video, character creator when making a character, video player when playing a video

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chromium 67.0.3396.87 (the one that came with wrapper offline
 - Version: stable
 - NPM Crash Log: There was no error that showed up in the npm crash log when the problem happened

**Additional context**
This same problem also happens when I go on any modded versions and any herokuapp versions and it thinks there is no swf files at all when there clearly is

Note: I use vyond legacy which is a modded version of wrapper offline that makes it look like vyond legacy, but everything else is the same as wrapper offline

Please find a way to help me fix this problem as it is only doing it to me, this problem never happened to me before my computer was reset

**Comment by LillianaxAnderson** [comment]
I think I found out the problem myself but I can't fix it

I think the problem I am having is http://localhost:4664 is not working for me so please can someone fix it

**Comment by octanuary** [comment]
this has been fixed in >=1.3.0
