### ISSUE TITLE
VoiceForge no longer working as of July 1st, 2022

### ISSUE THREAD

**Issue by siobhan-saoirse** [wrapper-offline/wrapper-offline#48]
I've checked the API and it simply results in an "Unauthorized" 401 error.

**Comment by siobhan-saoirse** [comment]
This has severely affected my website as the API has been changed.

**Comment by duckduckstab1** [comment]
VoiceForge API retired, RIP

**Comment by siobhan-saoirse** [comment]
the only way to use the API is through the mobile app ATM.

**Comment by duckduckstab1** [comment]
They did forget that, seems like desktop version is having a bad issue.

**Comment by HatcheryRoosters** [comment]
Hi will the VoiceForge issue be fixed in 2.0.0?

**Comment by HatcheryRoosters** [comment]
Is there a solution to fix the VoiceForge yet.

**Comment by siobhan-saoirse** [comment]
nope

**Comment by SimplyA-Coder** [comment]
i wonder if voiceforge is working again

**Comment by siobhan-saoirse** [comment]
no

**Comment by HatcheryRoosters** [comment]
> the only way to use the API is through the mobile app ATM.

Oh and there's gonna be a tax for anything VoiceForge.

**Comment by siobhan-saoirse** [comment]
i hope the devs realize i helped the project by fixing the voiceforge voices. but there is not much i can do about it now, it needs a google account to work properly

**Comment by SimplyA-Coder** [comment]
is voiceforge still working?

**Comment by HatcheryRoosters** [comment]
VoiceForge no longer works, their API was changed to nothing but a mobile
only scam that gets you bombarded with ads absolutely non-stop. The ads
never go away with any subscriptions bought by credit card fraud. The
endless barrage of ads here to stay. You will never get your voice clips,
you will never get that sweet and adorable Princess voice, or that goofy
ahhh funny Kidaroo or the fat man's Diesel EVER AGAIN.

**Comment by Visualwit** [comment]
Anyway to block the ads on the app?

**Comment by HatcheryRoosters** [comment]
Never will there be a way

**Comment by AzeemHadzrie** [comment]
There is a fix,

First, install BlueStacks.
Second, install both VoiceForge and personalDNSfilter on the Play Store.
Third, run personalDNSfilter first, wait for it to block ads then you can exit.
Fourth, run VoiceForge, and type anything you want in any voice.

Optional (if you want to record audio), use any sound recording software (e.g. Audacity and Moo0 Audio Recorder)

**Comment by siobhan-saoirse** [comment]
now we just have to figure out how to use it on PC without using an emulator

**Comment by ghost** [comment]
You can also use Bandicam, it now has an Audio Only option

**Comment by adampinco** [comment]
MY DISK SPACE IS DEAD GONE

**Comment by HybridTheGamerAndVideoMaker** [comment]
https://www.voiceforge.com/ 
isnt this the newer version of voiceforge?

**Comment by siobhan-saoirse** [comment]
yeah, but it's mobile only

**Comment by thetoonsofjosh** [comment]
Don't worry, there is hope now! Since Discord user unicom actually managed to bring back the VoiceForge voices on Wrapper: Offline, now rendering the voices usable again and no longer letting people forcing to use the app anymore.
https://cdn.discordapp.com/attachments/723289630111301642/1102640434762752142/tts.js

**Comment by Oceanboy1330** [comment]
Finally!

**Comment by HatcheryRoosters** [comment]
HOLD IT.

How do we replace it (I'm a Mac fella)

**Comment by Crawlerop** [comment]
> Don't worry, there is hope now! Since Discord user unicom actually managed to bring back the VoiceForge voices on Wrapper: Offline, now rendering the voices usable again and no longer letting people forcing to use the app anymore. https://cdn.discordapp.com/attachments/723289630111301642/1102640434762752142/tts.js

PR #162 readds VoiceForge support for now.

**Comment by beepcmd** [comment]
YEah it works
