### ISSUE TITLE
Custom assets not appearing in character creator

### ISSUE THREAD

**Issue by MKVollmer25** [wrapper-offline/wrapper-offline#50]
**Describe the bug**
Custom assets do not appear in the character creator when they are placed in the family folder in cc_store

**To Reproduce**
1. Download the custom assets mod
2. Replace the original family folder with the custom assets family folder
3. Enter the Comedy World character creator
4. Custom assets are missing

**Expected behavior**
The extra character items should've shown up in the character creator

**Desktop (please complete the following information):**
 - Windows 10
 - Ungoogled Chromium
 - Version 1.3.0

**Comment by ghost** [comment]
turn off auto updating
