### ISSUE TITLE
Custom Characters Won't Load

### ISSUE THREAD

**Issue by IAmJuDeM** [wrapper-offline/wrapper-offline#52]
**Describe the bug**
When I go to see the custom characters I made, whether that be in the Video Maker or the Character Browser, it just shows an infinitely spinning loading circle. I have waited on this circle for like 7 minutes but nothing changed and this didn't seem to help at all.

**To Reproduce**
1. Run Wrapper Offline (For some reason I have to run as admin or localhost error will always appear)
2. Do anything that would cause you to see the characters, like clicking on the "Create a Character" button or on the "Characters" section in the Video Maker
3. Infinitely loading spinning circle icon is shown, preventing the characters from being seen or used.

**Expected behavior**
The characters should load properly and not show a spinning circle.

**Screenshots**
![Screenshot (177)](https://user-images.githubusercontent.com/108896100/177850394-d430b49e-dd8a-4b16-9fc5-3a7689247565.png)
![Screenshot (178)](https://user-images.githubusercontent.com/108896100/177850403-c34b7731-ec59-46c6-b0e9-83eb387c3c0f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Wrapper Offline Browser
 - Version: 1.3.0

**Additional context**
A weird thing is that like every other menu loads as it should; the props, the fonts, etc. Only the Custom Characters list fails to do that. Also, this bug started randomly after I had already created some characters, and I went to add another character to my video, but Wrapper Offline froze, which isn't completely unusual. So I closed the application (Entered 0 on the command prompt, closed the browser and closed the command prompt), and when I opened Wrapper Offline again, the glitch began. I restarted it, tried changing my settings, tried making a new character to access the menu, and restarted my computer, but nothing worked.

**Comment by CreatorHouse** [comment]
does this work for mac and is there a video for this so i can understand this better.
