### ISSUE TITLE
The Paul tts voice doesn't work 

### ISSUE THREAD

**Issue by ghost** [wrapper-offline/wrapper-offline#58]
**Describe the bug**
When I use the Paul voice it refuses to let me use it as it loads forever

Update:
Somehow by deactivating discord rich presents it worked but i didn't have to do that before 

**To Reproduce**
1. Add in Paul voice to a business friendly character
2. loads forever

**Expected behavior**
I expected the voice the work you now!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: ungoogled chrome
 - Version beta, stable

**Comment by SimplyA-Coder** [comment]
Paul is a Vocalware voice, I think at the time Vocalware was under maintenance along with the text-to-speech API.
