### ISSUE TITLE
I can't seem to find any of the stock characters on the Lil Peepz/Lil Petz/Space Peepz theme!

### ISSUE THREAD

**Issue by Usernameisnotavailableformyself** [wrapper-offline/wrapper-offline#59]
![image](https://user-images.githubusercontent.com/109833660/180584023-1121f33a-8cf1-4844-9320-0355a53225ab.png) 
![image](https://user-images.githubusercontent.com/109833660/180584035-f085aadd-bb21-4d20-bc73-96925746c7e5.png)

Oddly enough, .pngs of the characters for Space Peepz and Lil Petz are on the thumbnails folder as seen here 
![image](https://user-images.githubusercontent.com/109833660/180584215-508ba8a3-29e5-48f7-8ed6-77fd3d5eafa6.png)

**Desktop:**
 - OS: Windows
 - Version 1.3.0

**Comment by SimplyA-Coder** [comment]
I have seen this in some themes, it's likely because of a misconfiguration or the .XML files were not uploaded into the server/characters folder path.

**Comment by SimplyA-Coder** [comment]
Edit: So apparently, the XML files for the characters don't even exist. Just the thumbnails. XML files for all the assets (hands, feet, accessories, hair) and thumbnails create a character. The theme's XML file probably doesn't have any tag <char/>, which shows there are no characters. I'm sure there's a fix for this online
