### ISSUE TITLE
(1.3.0) Server keeps losing connection

### ISSUE THREAD

**Issue by ghost** [wrapper-offline/wrapper-offline#64]
**Describe the bug**
Every few minutes, the local server keeps losing connection so I can't save, preview, reopen the video list, or make characters.
**To Reproduce**
1. Use Wrapper: offline for a few minutes

**Expected behavior**
Cannot preview or save videos, cannot make custom characters, cannot generate robot voices to use with videos, cannot reopen video list.

**Screenshots**
I don't have any screenshots of this error.

**Desktop (please complete the following information):**
 - OS: Windows 11 Home
 - Browser: ballistic, ungoogled Chromium
 - Version Stable 1.3.0

**Additional context**
Wrapper: Offline temporarily fixes itself when closing and reopening, but it will always reproduce. It makes it very hard to do my newest video that is in the works.

**Comment by NeonHaiiroookami** [comment]
agree

**Comment by ghost** [comment]
The issue seems to be caused by trying to generate certain voices.

**Comment by NeonHaiiroookami** [comment]
not only that but also the character creator

**Comment by SimplyA-Coder** [comment]
Well, if you're using a Nuance or VoiceForge/Cepstral voice, the APIs for those voices don't work right now, which can crash Node.js code and crash W:O.

**Comment by ghost** [comment]
Oh, so it's Node.JS that's causing the connection loss.

**Comment by ghost** [comment]
Version 2.0.0 on GitHub corrected this issue.
