### ISSUE TITLE
(2.0.0) Inspect element pane starts showing up

### ISSUE THREAD

**Issue by NeonHaiiroookami** [wrapper-offline/wrapper-offline#66]
**Describe the Bug:**
I just downloaded Wrapper: Offline 2.0.0 beta and opened `Wrapper Offline.exe`...

**To Reproduce:**
1. Double-click on `Wrapper Offline.exe`, it's located in `Wrapper Offline-win32-x64`
2. Look on the right side of the opened window.

**Expected Behavior:**
It automatically opens the "Inspect element" pane...

**Video Recording:**
https://user-images.githubusercontent.com/111209874/186043339-4ca2c0a6-7222-4614-a27d-4b1d0e6545c6.mp4

**Desktop:**
 - OS: Windows 11
 - Browser: Ungoogled Chrome
 - Version: 2.0.0 Beta

**Comment by BunnyTub** [comment]
might just be because it's a pre-release,
for debugging

that's prob why

**Comment by NeonHaiiroookami** [comment]
oh ok
