### ISSUE TITLE
Wrapper: Offline 1.4.0 not installing Flash Player

### ISSUE THREAD

**Issue by SimplyA-Coder** [wrapper-offline/wrapper-offline#73]
**Bug Description**
So, I uninstalled AFP from my PC, and the W:O installer is trying hard to get Flash Player back, but It never does. It says to restart the installer, so I do it, and now I'm stuck in an infinite installation loop.

**To Reproduce**
To reproduce the steps:
1. Install any version of W:O in the installer
2. If AFP isn't installed, continue the installation
3. It will write the Web Request Stream, then AFP never installs

**Desktop (please complete the following information):**
 - OS: Windows 10+
 - Version: Beta

https://user-images.githubusercontent.com/107278351/189249404-61f5e271-da35-473e-843c-95cbd5d8f3d0.mp4

**Comment by mimmomarsala** [comment]
I have the same problem

**Comment by SimplyA-Coder** [comment]
I downloaded the main 1.3.0 version manually from GitHub and used WinRAR to extract it...It just isn't the same

**Comment by SimplyA-Coder** [comment]
@GoTest334 do u know a solution to this problem
