### ISSUE TITLE
RunAsTI as a virus?

### ISSUE THREAD

**Issue by jaigitrep159** [Wrapper-Offline/wrapper-offline#89]
windows defender detected me as a virus from RunAsTI tho. 
Proofs: 
https://github.com/jschicht/RunAsTI/issues/9

https://github.com/gerardog/gsudo/issues/49

**Comment by imageny** [comment]
That's definitely a false positive. You may need to add the directory to it on the whitelist in your antivirus program.

**Comment by jaigitrep159** [comment]
yea

**Comment by jaigitrep159** [comment]
but how

**Comment by jaigitrep159** [comment]
ok  but thanks
