### ISSUE TITLE
asset importer won't open for 32-bit windows architecture

### ISSUE THREAD

**Issue by jaigitrep159** [Wrapper-Offline/wrapper-offline#92]
https://user-images.githubusercontent.com/76834328/121469100-79ee6c80-c9ee-11eb-9290-8d0a5339a240.mp4

**Comment by imageny** [comment]
https://answers.microsoft.com/en-us/windows/forum/windows_10-power-winpc/this-app-cant-run-on-your-pc/d4869176-98fa-45b7-baf9-23c083335148

https://www.majorgeeks.com/content/page/this_app_cant_run_on_your_pc.html

Try any of these methods and let me know if it works.

**Comment by jaigitrep159** [comment]
ok

**Comment by zoccorus** [comment]
close???

**Comment by zoccorus** [comment]
@RegularSpark close this

**Comment by RedBoiOfficial** [comment]
> @RegularSpark close this
umm bruh
