### ISSUE TITLE
Some voices not working...

### ISSUE THREAD

**Issue by alexmidis** [Wrapper-Offline/wrapper-offline#93]
Some voices such as Jennifer don't work at all right now.

I have tested this in 3 different versions of W:O, v1.2.1, v1.2.3, and v1.3.1b10.

They return a error message saying "Unable to retrieve MP3 stream." or "Something broke and got grounded.".

**Comment by zoccorus** [comment]
u r using 1.2.2 version. update to 1.3.1

**Comment by alexmidis** [comment]
I've already tried that version, still getting the same errors :/

**Comment by Thunderzapper** [comment]
ivonia voices arent working atm due to a change with their website
